import { ChapterData } from "./types";

const baseChapters: ChapterData[] = [
  {
    id: 1,
    name: "Bab 1",
    cards: [
      { kanji: "私", hiragana: "わたし", romaji: "watashi", meaning: "saya" },
      { hiragana: "あなた", romaji: "anata", meaning: "Anda" },
      { kanji: "あの人（あの方）", hiragana: "あの ひと（あの かた）", romaji: "ano hito (ano kata)", meaning: "orang itu, beliau (あのかた adalah bentuk sopan dari あのひと)" },
      { kanji: "〜さん", hiragana: "〜さん", romaji: "~san", meaning: "Sdr. ~, Bapak ~, Ibu ~ (akhiran untuk mengekspresikan kesopanan yang diletakkan di belakang nama orang)" },
      { hiragana: "〜ちゃん", romaji: "~chan", meaning: "(akhiran yang dipakai untuk anak laki-laki dan anak perempuan sebagai pengganti ~さん yang diletakkan di belakang nama anak)" },
      { kanji: "〜人", hiragana: "〜じん", romaji: "~jin", meaning: "orang ~ (akhiran yang menyatakan warga negara. Contoh: アメリカじん orang Amerika Serikat)" },
      { kanji: "先生", hiragana: "せんせい", romaji: "sensei", meaning: "guru, dosen (tidak dipakai jika menyebutkan pekerjaan sendiri)" },
      { kanji: "教師", hiragana: "きょうし", romaji: "kyoushi", meaning: "guru, dosen" },
      { kanji: "学生", hiragana: "がくせい", romaji: "gakusei", meaning: "mahasiswa" },
      { kanji: "会社員", hiragana: "かいしゃいん", romaji: "kaishain", meaning: "karyawan perusahaan" },
      { kanji: "社員", hiragana: "しゃいん", romaji: "shain", meaning: "karyawan perusahaan (dipakai bersama dengan nama perusahaan. Contoh: IMCの しゃいん (karyawan perusahaan IMC))" },
      { kanji: "銀行員", hiragana: "ぎんこういん", romaji: "ginkouin", meaning: "pegawai bank" },
      { kanji: "医者", hiragana: "いしゃ", romaji: "isha", meaning: "dokter" },
      { kanji: "研究者", hiragana: "けんきゅうしゃ", romaji: "kenkyuusha", meaning: "peneliti" },
      { kanji: "大学", hiragana: "だいがく", romaji: "daigaku", meaning: "universitas" },
      { kanji: "病院", hiragana: "びょういん", romaji: "byouin", meaning: "rumah sakit" },
      { hiragana: "だれ（どなた）", romaji: "dare (donata)", meaning: "siapa (どなた adalah bentuk sopan dari だれ)" },
      { kanji: "ー歳", hiragana: "ーさい", romaji: "-sai", meaning: "- tahun" },
      { kanji: "何歳（おいくつ）", hiragana: "なんさい（おいくつ）", romaji: "nansai (oikutsu)", meaning: "umur berapa (おいくつ adalah bentuk sopan dari なんさい)" },
      { hiragana: "はい", romaji: "hai", meaning: "ya" },
      { hiragana: "いいえ", romaji: "iie", meaning: "tidak, bukan" },
      { kanji: "初めまして。", hiragana: "はじめまして。", romaji: "Hajimemashite.", meaning: "Perkenalkan. (ucapan salam pada waktu pertama kali berkenalan)" },
      { kanji: "〜から来ました。", hiragana: "〜からきました。", romaji: "~kara kimashita.", meaning: "datang dari ~, berasal dari ~" },
      { kanji: "［どうぞ］よろしく［お願いします］。", hiragana: "［どうぞ］よろしく［おねがいします］。", romaji: "[douzo] yoroshiku [onegaishimasu].", meaning: "Salam kenal. (ucapan terakhir untuk perkenalkan diri)" },
      { kanji: "失礼ですが", hiragana: "しつれいですが", romaji: "Shitsureidesuga", meaning: "permisi, maaf (digunakan ketika bertanya tentang hal yang pribadi seperti nama, alamat dan sebagainya)" },
      { kanji: "お名前は？", hiragana: "おなまえは？", romaji: "Onamaewa?", meaning: "Siapa namanya?" },
      { hiragana: "こちらは〜さんです。", romaji: "Kochirawa ~sandesu.", meaning: "Ini Bapak ~./Ini Ibu, Sdr. ~." }
    ]
  },
  {
    id: 2,
    name: "Bab 2",
    cards: [
      { hiragana: "これ", romaji: "kore", meaning: "ini (benda yang ada di dekat si pembicara)" },
      { hiragana: "それ", romaji: "sore", meaning: "itu (benda yang ada di dekat lawan bicara)" },
      { hiragana: "あれ", romaji: "are", meaning: "itu (benda yang ada jauh dari si pembicara dan lawan bicara)" },
      { hiragana: "この〜", romaji: "kono~", meaning: "~ ini (menerangkan benda atau orang yang ada di dekat si pembicara.)" },
      { hiragana: "その〜", romaji: "sono~", meaning: "~ itu (menerangkan benda atau orang yang ada di dekat lawan bicara.)" },
      { hiragana: "あの〜", romaji: "ano~", meaning: "~ itu (menerangkan benda atau orang yang ada jauh dari si pembicara dan lawan bicara.)" },
      { kanji: "本", hiragana: "ほん", romaji: "hon", meaning: "buku" },
      { kanji: "辞書", hiragana: "じしょ", romaji: "jisho", meaning: "kamus" },
      { kanji: "雑誌", hiragana: "ざっし", romaji: "zasshi", meaning: "majalah" },
      { kanji: "新聞", hiragana: "しんぶん", romaji: "shinbun", meaning: "koran, surat kabar" },
      { hiragana: "ノート", romaji: "nooto", meaning: "buku tulis, buku catatan" },
      { kanji: "手帳", hiragana: "てちょう", romaji: "techou", meaning: "buku agenda" },
      { kanji: "名刺", hiragana: "めいし", romaji: "meishi", meaning: "kartu nama" },
      { hiragana: "カード", romaji: "kaado", meaning: "kartu" },
      { kanji: "鉛筆", hiragana: "えんぴつ", romaji: "enpitsu", meaning: "pensil" },
      { hiragana: "ボールペン", romaji: "boorupen", meaning: "bolpoin" },
      { hiragana: "シャープペンシル", romaji: "shaapupenshiru", meaning: "pensil mekanik, pensil isi ulang" },
      { hiragana: "かぎ", romaji: "kagi", meaning: "kunci" },
      { kanji: "時計", hiragana: "とけい", romaji: "tokei", meaning: "jam, arloji" },
      { kanji: "傘", hiragana: "かさ", romaji: "kasa", meaning: "payung" },
      { kanji: "かばん", hiragana: "かばん", romaji: "kaban", meaning: "tas" },
      { hiragana: "CD", romaji: "shiidii", meaning: "CD" },
      { hiragana: "テレビ", romaji: "terebi", meaning: "televisi" },
      { hiragana: "ラジオ", romaji: "rajio", meaning: "radio" },
      { hiragana: "カメラ", romaji: "kamera", meaning: "kamera" },
      { hiragana: "コンピューター", romaji: "konpyuutaa", meaning: "komputer, PC" },
      { kanji: "車", hiragana: "くるま", romaji: "kuruma", meaning: "mobil" },
      { kanji: "机", hiragana: "つくえ", romaji: "tsukue", meaning: "meja, meja tulis" },
      { hiragana: "いす", romaji: "isu", meaning: "kursi" },
      { hiragana: "チョコレート", romaji: "chokoreeto", meaning: "coklat" },
      { hiragana: "コーヒー", romaji: "koohii", meaning: "kopi" },
      { kanji: "［お］土産", hiragana: "［お］みやげ", romaji: "[o]miyage", meaning: "oleh-oleh" },
      { kanji: "英語", hiragana: "えいご", romaji: "eigo", meaning: "bahasa Inggris" },
      { kanji: "日本語", hiragana: "にほんご", romaji: "nihongo", meaning: "bahasa Jepang" },
      { kanji: "〜語", hiragana: "〜ご", romaji: "~go", meaning: "bahasa ~" },
      { kanji: "何", hiragana: "なん", romaji: "nan", meaning: "apa" },
      { hiragana: "そう", romaji: "sou", meaning: "begitu" },
      { hiragana: "あのう", romaji: "anou", meaning: "Eee... (ungkapan yang digunakan kepada lawan bicara dalam perasaan ragu-ragu)" },
      { hiragana: "えっ", romaji: "e", meaning: "Eh (dipakai ketika mendengar sesuatu yang di luar dugaan)" },
      { hiragana: "どうぞ。", romaji: "Douzo.", meaning: "Silakan. (digunakan ketika menawarkan sesuatu (barang))" },
      { hiragana: "［どうも］ありがとう［ございます］。", romaji: "[doumo] arigatou [gozaimasu].", meaning: "Terima kasih (banyak)." },
      { hiragana: "そうですか。", romaji: "Soudesuka.", meaning: "O, begitu./O, ya." },
      { kanji: "違います。", hiragana: "ちがいます。", romaji: "Chigaimasu.", meaning: "Bukan./Tidak./Salah." },
      { hiragana: "あ", romaji: "a", meaning: "O, Eh, (dipakai ketika sadar)" },
      { kanji: "これから お世話になります。", hiragana: "これから おせわになります。", romaji: "Korekara osewaninarimasu.", meaning: "Mulai sekarang, saya akan meminta bantuannya." },
      { kanji: "こちらこそ［どうぞ］よろしく［お願いします］。", hiragana: "こちらこそ［どうぞ］よろしく［おねがいします］。", romaji: "Kochirakoso [douzo] yoroshiku [onegaishimasu].", meaning: "Ya, sama-sama. (jawaban terhadap [どうぞ] よろしく [おねがいします].)" }
    ]
  },
  {
    id: 3,
    name: "Bab 3",
    cards: [
      { hiragana: "ここ", romaji: "koko", meaning: "sini" },
      { hiragana: "そこ", romaji: "soko", meaning: "situ" },
      { hiragana: "あそこ", romaji: "asoko", meaning: "sana" },
      { hiragana: "どこ", romaji: "doko", meaning: "(di) mana" },
      { hiragana: "こちら", romaji: "kochira", meaning: "sini (bentuk sopan dari ここ)" },
      { hiragana: "そちら", romaji: "sochira", meaning: "situ (bentuk sopan dari そこ)" },
      { hiragana: "あちら", romaji: "achira", meaning: "sana (bentuk sopan dari あそこ)" },
      { hiragana: "どちら", romaji: "dochira", meaning: "mana (bentuk sopan dari どこ)" },
      { kanji: "教室", hiragana: "きょうしつ", romaji: "kyoushitsu", meaning: "ruang kelas" },
      { kanji: "食堂", hiragana: "しょくどう", romaji: "shokudou", meaning: "ruang makan, rumah makan, kantin" },
      { kanji: "事務所", hiragana: "じむしょ", romaji: "jimusho", meaning: "kantor" },
      { kanji: "会議室", hiragana: "かいぎしつ", romaji: "kaigishitsu", meaning: "ruang rapat" },
      { kanji: "受付", hiragana: "うけつけ", romaji: "uketsuke", meaning: "meja informasi" },
      { hiragana: "ロビー", romaji: "robii", meaning: "ruang tunggu, lobi" },
      { kanji: "部屋", hiragana: "へや", romaji: "heya", meaning: "kamar" },
      { kanji: "トイレ（お手洗い）", hiragana: "トイレ（おてあらい）", romaji: "toire (otearai)", meaning: "kamar kecil, toilet, W.C." },
      { kanji: "階段", hiragana: "かいだん", romaji: "kaidan", meaning: "tangga" },
      { hiragana: "エレベーター", romaji: "erebeetaa", meaning: "lift" },
      { hiragana: "エスカレーター", romaji: "esukareetaa", meaning: "tangga berjalan, eskalator" },
      { kanji: "自動販売機", hiragana: "じどうはんばいき", romaji: "jidouhanbaiki", meaning: "mesin jual otomatis" },
      { kanji: "電話", hiragana: "でんわ", romaji: "denwa", meaning: "telepon" },
      { kanji: "［お］国", hiragana: "［お］くに", romaji: "[o]kuni", meaning: "negara, negeri" },
      { kanji: "会社", hiragana: "かいしゃ", romaji: "kaisha", meaning: "perusahaan" },
      { hiragana: "うち", romaji: "uchi", meaning: "rumah" },
      { kanji: "靴", hiragana: "くつ", romaji: "kutsu", meaning: "sepatu" },
      { hiragana: "ネクタイ", romaji: "nekutai", meaning: "dasi" },
      { hiragana: "ワイン", romaji: "wain", meaning: "anggur" },
      { kanji: "売り場", hiragana: "うりば", romaji: "uriba", meaning: "tempat penjualan" },
      { kanji: "地下", hiragana: "ちか", romaji: "chika", meaning: "bawah tanah, basement" },
      { kanji: "ー階", hiragana: "ーかい（ーがい）", romaji: "-kai (-gai)", meaning: "lantai -, tingkat -" },
      { kanji: "何階", hiragana: "なんがい", romaji: "nangai", meaning: "lantai berapa, tingkat berapa" },
      { kanji: "ー円", hiragana: "ーえん", romaji: "-en", meaning: "- yen" },
      { hiragana: "いくら", romaji: "ikura", meaning: "berapa" },
      { kanji: "百", hiragana: "ひゃく", romaji: "hyaku", meaning: "ratus" },
      { kanji: "千", hiragana: "せん", romaji: "sen", meaning: "ribu" },
      { kanji: "万", hiragana: "まん", romaji: "man", meaning: "puluh ribu" },
      { hiragana: "すみません。", romaji: "Sumimasen.", meaning: "Maaf./Permisi." },
      { hiragana: "どうも。", romaji: "Doumo.", meaning: "Terima kasih." },
      { hiragana: "いらっしゃいませ。", romaji: "Irasshaimase.", meaning: "Selamat datang./Bisa saya bantu? (ungkapan kepada tamu yang masuk ke toko)" },
      { kanji: "［〜を］見せてください。", hiragana: "［〜を］みせてください。", romaji: "[~o] misetekudasai.", meaning: "Tolong perlihatkan [~]." },
      { hiragana: "じゃ", romaji: "ja", meaning: "Baiklah, kalau begitu," },
      { hiragana: "［〜を］ください。", romaji: "[~o] kudasai.", meaning: "Minta [~]./Tolong berikan [~]." }
    ]
  },
  {
    id: 18,
    name: "Bab 18",
    cards: [
      { hiragana: "できます", romaji: "dekimasu", meaning: "dapat, bisa, mampu" },
      { kanji: "洗います", hiragana: "あらいます", romaji: "araimasu", meaning: "mencuci" },
      { kanji: "弾きます", hiragana: "ひきます", romaji: "hikimasu", meaning: "bermain (untuk bermain alat musik senar dan piano)" },
      { kanji: "歌います", hiragana: "うたいます", romaji: "utaimasu", meaning: "bernyanyi, menyanyi" },
      { kanji: "集めます", hiragana: "あつめます", romaji: "atsumemasu", meaning: "mengumpulkan" },
      { kanji: "捨てます", hiragana: "すてます", romaji: "sutemasu", meaning: "membuang" },
      { kanji: "換えます", hiragana: "かえます", romaji: "kaemasu", meaning: "mengganti, menukar" },
      { kanji: "運転します", hiragana: "うんてんします", romaji: "untenshimasu", meaning: "menyetir, mengendarai" },
      { kanji: "予約します", hiragana: "よやくします", romaji: "yoyakushimasu", meaning: "memesan" },
      { kanji: "現金", hiragana: "げんきん", romaji: "genkin", meaning: "uang tunai" },
      { kanji: "趣味", hiragana: "しゅみ", romaji: "shumi", meaning: "hobi, kegemaran" },
      { kanji: "日記", hiragana: "にっき", romaji: "nikki", meaning: "catatan harian" },
      { kanji: "お祈り", hiragana: "おいのり", romaji: "oinori", meaning: "doa (〜を します : berdoa)" },
      { kanji: "課長", hiragana: "かちょう", romaji: "kachou", meaning: "kepala seksi" },
      { kanji: "部長", hiragana: "ぶちょう", romaji: "buchou", meaning: "kepala bagian" },
      { kanji: "社長", hiragana: "しゃちょう", romaji: "shachou", meaning: "direktur utama" },
      { kanji: "動物", hiragana: "どうぶつ", romaji: "doubutsu", meaning: "hewan, binatang" },
      { kanji: "馬", hiragana: "うま", romaji: "uma", meaning: "kuda" },
      { hiragana: "インターネット", romaji: "intaanetto", meaning: "internet" },
      { hiragana: "ピアノ", romaji: "piano", meaning: "piano" },
      { hiragana: "ーメートル", romaji: "-meetoru", meaning: "~ meter" },
      { kanji: "特に", hiragana: "とくに", romaji: "tokuni", meaning: "terutama, khususnya" },
      { hiragana: "ぜひ", romaji: "zehi", meaning: "benar-benar, mesti" },
      { hiragana: "なかなか", romaji: "nakanaka", meaning: "jarang, tidak mudah (diikuti bentuk negatif)" },
      { hiragana: "ほんとうですか。", romaji: "hontoudesuka.", meaning: "Betul?/Benar?" },
      { hiragana: "それはおもしろいですね。", romaji: "sore wa omoshiroidesune.", meaning: "Itu menarik ya." },
      { hiragana: "へえ", romaji: "hee", meaning: "Betul ya?/Benar ya?/Masa! (digunakan ketika terkagum atau terkejut)" }
    ]
  },
  {
    id: 19,
    name: "Bab 19",
    cards: [
      { kanji: "登ります、上ります", hiragana: "のぼります", romaji: "noborimasu", meaning: "naik" },
      { kanji: "泊まります", hiragana: "とまります", romaji: "tomarimasu", meaning: "menginap [di hotel]" },
      { kanji: "掃除します", hiragana: "そうじします", romaji: "soujishimasu", meaning: "membersihkan" },
      { kanji: "洗濯します", hiragana: "せんたくします", romaji: "sentakushimasu", meaning: "mencuci pakaian" },
      { hiragana: "なります", romaji: "narimasu", meaning: "menjadi" },
      { kanji: "眠い", hiragana: "ねむい", romaji: "nemui", meaning: "mengantuk" },
      { kanji: "強い", hiragana: "つよい", romaji: "tsuyoi", meaning: "kuat" },
      { kanji: "弱い", hiragana: "よわい", romaji: "yowai", meaning: "lemah" },
      { kanji: "練習", hiragana: "れんしゅう", romaji: "renshuu", meaning: "latihan (〜[を] します : berlatih)" },
      { hiragana: "ゴルフ", romaji: "gorufu", meaning: "golf (〜[を] します : bermain golf)" },
      { kanji: "相撲", hiragana: "すもう", romaji: "sumou", meaning: "sumo (〜[を] します : bermain sumo)" },
      { kanji: "お茶", hiragana: "おちゃ", romaji: "ocha", meaning: "upacara minum teh" },
      { kanji: "日", hiragana: "ひ", romaji: "hi", meaning: "hari" },
      { kanji: "調子", hiragana: "ちょうし", romaji: "choushi", meaning: "kondisi" },
      { kanji: "一度", hiragana: "いちど", romaji: "ichido", meaning: "sekali" },
      { kanji: "一度も", hiragana: "いちども", romaji: "ichidomo", meaning: "sekali-kali, satu kali pun (diikuti bentuk negatif)" },
      { hiragana: "だんだん", romaji: "dandan", meaning: "berangsur-angsuran, lama-kelamaan" },
      { hiragana: "もうすぐ", romaji: "mousugu", meaning: "tidak lama lagi" },
      { hiragana: "おかげさまで", romaji: "okagesamade", meaning: "atas berkat (ucapan yang digunakan ketika menyatakan rasa terima kasih atas bantuan atau kebaikan hati dari orang)" },
      { hiragana: "でも", romaji: "demo", meaning: "tetapi" },
      { kanji: "乾杯", hiragana: "かんぱい", romaji: "kanpai", meaning: "toast" },
      { hiragana: "ダイエット", romaji: "daietto", meaning: "diet (〜を します : berdiet)" },
      { kanji: "無理[な]", hiragana: "むり[な]", romaji: "muri[na]", meaning: "paksa, berlebihan" },
      { kanji: "体にいい", hiragana: "からだにいい", romaji: "karadaniii", meaning: "baik untuk tubuh" }
    ]
  },
  {
    id: 20,
    name: "Bab 20",
    cards: [
      { kanji: "要ります", hiragana: "いります", romaji: "irimasu", meaning: "memerlukan [VISA]" },
      { kanji: "調べます", hiragana: "しらべます", romaji: "shirabemasu", meaning: "memeriksa, meneliti, mengecek" },
      { kanji: "修理します", hiragana: "しゅうりします", romaji: "shuurishimasu", meaning: "memperbaiki" },
      { kanji: "僕", hiragana: "ぼく", romaji: "boku", meaning: "aku (dipakai oleh laki-laki, kata ganti informal dari わたし)" },
      { kanji: "君", hiragana: "きみ", romaji: "kimi", meaning: "kamu (bentuk informal untuk あなた, digunakan terhadap orang yang setaraf atau di bawah si pembicara)" },
      { kanji: "〜君", hiragana: "〜くん", romaji: "~kun", meaning: "Sdr. 〜 (bentuk informal untuk さん, digunakan terhadap orang yang setaraf atau di bawah si pembicara, sering digunakan untuk nama anak laki-laki)" },
      { hiragana: "うん", romaji: "un", meaning: "ya (bentuk informal dari はい)" },
      { hiragana: "ううん", romaji: "uun", meaning: "tidak, bukan (bentuk informal dari いいえ)" },
      { hiragana: "ことば", romaji: "kotoba", meaning: "kata, bahasa" },
      { kanji: "着物", hiragana: "きもの", romaji: "kimono", meaning: "kimono (pakaian tradisional Jepang)" },
      { hiragana: "ビザ", romaji: "biza", meaning: "VISA" },
      { kanji: "初め", hiragana: "はじめ", romaji: "hajime", meaning: "awal, mula-mula" },
      { kanji: "終わり", hiragana: "おわり", romaji: "owari", meaning: "akhir" },
      { hiragana: "こっち", romaji: "kocchi", meaning: "sini (ungkapan informal dari kata こちら)" },
      { hiragana: "そっち", romaji: "socchi", meaning: "situ (ungkapan informal dari kata そちら)" },
      { hiragana: "あっち", romaji: "acchi", meaning: "sana (ungkapan informal dari kata あちら)" },
      { hiragana: "どっち", romaji: "docchi", meaning: "mana (ungkapan informal untuk kata どちら)" },
      { hiragana: "みんなで", romaji: "minnade", meaning: "kita semua, kita sama-sama" },
      { hiragana: "〜けど", romaji: "~kedo", meaning: "〜 tetapi (ungkapan informal dari が)" },
      { hiragana: "おなかがいっぱいです", romaji: "onaka ga ippaidesu", meaning: "sudah kenyang" },
      { hiragana: "よかったら", romaji: "yokattara", meaning: "kalau mau, kalau suka" },
      { hiragana: "いろいろ", romaji: "iroiro", meaning: "macam-macam" }
    ]
  },
  {
    id: 21,
    name: "Bab 21",
    cards: [
      { kanji: "思います", hiragana: "おもいます", romaji: "omoimasu", meaning: "mengira, berpikir" },
      { kanji: "言います", hiragana: "いいます", romaji: "iimasu", meaning: "mengatakan, berkata" },
      { kanji: "勝ちます", hiragana: "かちます", romaji: "kachimasu", meaning: "menang" },
      { kanji: "負けます", hiragana: "まけます", romaji: "makemasu", meaning: "kalah" },
      { hiragana: "あります", romaji: "arimasu", meaning: "ada, diadakan [pesta perayaan] [お祭りが〜]" },
      { kanji: "役に立ちます", hiragana: "やくにたちます", romaji: "yakuni tachimasu", meaning: "berguna, bermanfaat" },
      { kanji: "動きます", hiragana: "うごきます", romaji: "ugokimasu", meaning: "pindah, bergerak" },
      { kanji: "やめます", hiragana: "やめます", romaji: "yamemasu", meaning: "berhenti [kerja] [会社を〜]" },
      { kanji: "気をつけます", hiragana: "きをつけます", romaji: "ki o tsukemasu", meaning: "berwaspada, berhati-hati" },
      { kanji: "留学します", hiragana: "りゅうがくします", romaji: "ryuugakushimasu", meaning: "studi di luar negeri" },
      { hiragana: "むだ[な]", romaji: "muda[na]", meaning: "sia-sia, tidak berguna" },
      { kanji: "不便[な]", hiragana: "ふべん[な]", romaji: "fuben[na]", meaning: "tidak praktis" },
      { hiragana: "すごい", romaji: "sugoi", meaning: "hebat, bukan main (digunakan ketika menyatakan kejutan atau kekaguman)" },
      { hiragana: "ほんとう", romaji: "hontou", meaning: "betul, benar" },
      { hiragana: "うそ", romaji: "uso", meaning: "bohong" },
      { kanji: "自動車", hiragana: "じどうしゃ", romaji: "jidousha", meaning: "mobil" },
      { kanji: "交通", hiragana: "こうつう", romaji: "koutsuu", meaning: "lalu lintas" },
      { kanji: "物価", hiragana: "ぶっか", romaji: "bukka", meaning: "harga barang" },
      { kanji: "放送", hiragana: "ほうそう", romaji: "housou", meaning: "siaran, pengumuman" },
      { hiragana: "ニュース", romaji: "nyuusu", meaning: "warta berita" },
      { hiragana: "アニメ", romaji: "anime", meaning: "animasi" },
      { hiragana: "マンガ", romaji: "manga", meaning: "manga, komik" },
      { hiragana: "デザイン", romaji: "dezain", meaning: "desain, model" },
      { kanji: "夢", hiragana: "ゆめ", romaji: "yume", meaning: "mimpi" },
      { kanji: "天才", hiragana: "てんさい", romaji: "tensai", meaning: "genius" },
      { kanji: "試合", hiragana: "しあい", romaji: "shiai", meaning: "pertandingan (〜をします: bertanding)" },
      { kanji: "意見", hiragana: "いけん", romaji: "iken", meaning: "pendapat" },
      { kanji: "話", hiragana: "はなし", romaji: "hanashi", meaning: "cerita (〜をします: bercerita, berbicara)" },
      { kanji: "地球", hiragana: "ちきゅう", romaji: "chikyuu", meaning: "bumi" },
      { kanji: "月", hiragana: "つき", romaji: "tsuki", meaning: "bulan" },
      { kanji: "最近", hiragana: "さいきん", romaji: "saikin", meaning: "akhir-akhir ini" },
      { hiragana: "たぶん", romaji: "tabun", meaning: "mungkin, barangkali" },
      { hiragana: "きっと", romaji: "kitto", meaning: "pasti" },
      { hiragana: "ほんとうに", romaji: "hontouni", meaning: "betul-betul" },
      { hiragana: "そんなに", romaji: "sonnani", meaning: "tidak begitu (diikuti bentuk negatif)" },
      { hiragana: "〜について", romaji: "~ni tsuite", meaning: "tentang ~, mengenai ~" },
      { kanji: "久しぶりですね。", hiragana: "ひさしぶりですね。", romaji: "Hisashiburidesune.", meaning: "Sudah lama tidak bertemu ya." },
      { kanji: "〜でも飲みませんか。", hiragana: "〜でものみませんか。", romaji: "~demo nomimasenka.", meaning: "Bagaimana kalau kita minum ~, atau apa saja?" },
      { hiragana: "もちろん", romaji: "mochiron", meaning: "tentu saja" },
      { kanji: "もう帰らないと……。", hiragana: "もうかえらないと……。", romaji: "Mou kaeranaito......", meaning: "Saya harus pulang..." }
    ]
  },
  {
    id: 26,
    name: "Bab 26",
    cards: [
      { kanji: "見ます、診ます", hiragana: "みます", romaji: "mimasu", meaning: "melihat, memeriksa" },
      { kanji: "探します、捜します", hiragana: "さがします", romaji: "sagashimasu", meaning: "mencari" },
      { kanji: "遅れます", hiragana: "おくれます", romaji: "okuremasu", meaning: "terlambat [pada waktu]" },
      { kanji: "間に合います", hiragana: "まにあいます", romaji: "maniaimasu", meaning: "sempat [pada waktu]" },
      { hiragana: "やります", romaji: "yarimasu", meaning: "melakukan" },
      { kanji: "拾います", hiragana: "ひろいます", romaji: "hiroimasu", meaning: "mendapat, mengambil" },
      { kanji: "連絡します", hiragana: "れんらくします", romaji: "renrakushimasu", meaning: "menghubungi" },
      { kanji: "気分がいい", hiragana: "きぶんがいい", romaji: "kibun ga ii", meaning: "rasa enak, segar" },
      { kanji: "気分が悪い", hiragana: "きぶんがわるい", romaji: "kibun ga warui", meaning: "rasa tidak enak" },
      { kanji: "運動会", hiragana: "うんどうかい", romaji: "undoukai", meaning: "lomba olahraga" },
      { kanji: "盆踊り", hiragana: "ぼんおどり", romaji: "bon-odori", meaning: "tarian Bon" },
      { hiragana: "フリーマーケット", romaji: "furiimaaketto", meaning: "pasar rombengan" },
      { kanji: "場所", hiragana: "ばしょ", romaji: "basho", meaning: "tempat" },
      { hiragana: "ボランティア", romaji: "borantia", meaning: "sukarelawan" },
      { kanji: "財布", hiragana: "さいふ", romaji: "saifu", meaning: "dompet" },
      { hiragana: "ごみ", romaji: "gomi", meaning: "sampah" },
      { kanji: "国会議事堂", hiragana: "こっかいぎじどう", romaji: "kokkai-gijidou", meaning: "gedung parlemen" },
      { kanji: "平日", hiragana: "へいじつ", romaji: "heijitsu", meaning: "hari kerja" },
      { kanji: "〜弁", hiragana: "〜べん", romaji: "~ben", meaning: "dialek ~" },
      { kanji: "今度", hiragana: "こんど", romaji: "kondo", meaning: "kali ini, lain kali" },
      { hiragana: "ずいぶん", romaji: "zuibun", meaning: "sangat, amat" },
      { kanji: "直接", hiragana: "ちょくせつ", romaji: "chokusetsu", meaning: "langsung" },
      { hiragana: "いつでも", romaji: "itsudemo", meaning: "kapan saja" },
      { hiragana: "どこでも", romaji: "dokodemo", meaning: "di mana-mana" },
      { hiragana: "だれでも", romaji: "daredemo", meaning: "siapa saja" },
      { kanji: "何でも", hiragana: "なんでも", romaji: "nandemo", meaning: "apa saja" },
      { hiragana: "こんな 〜", romaji: "konna ~", meaning: "~ begini" },
      { hiragana: "そんな 〜", romaji: "sonna ~", meaning: "~ begitu (dekat dari lawan bicara)" },
      { hiragana: "あんな 〜", romaji: "anna ~", meaning: "~ begitu (jauh dari si pembicara dan lawan bicara)" },
      { hiragana: "エドヤストア", romaji: "edoyasutoa", meaning: "toko fiksi" },
      { kanji: "片づきます", hiragana: "かたづきます", romaji: "katadzukimasu", meaning: "membereskan [barang]" },
      { kanji: "出します", hiragana: "だします", romaji: "dashimasu", meaning: "membuang [sampah], mengeluarkan" },
      { kanji: "燃えるごみ", hiragana: "もえるごみ", romaji: "moeru gomi", meaning: "sampah organik" },
      { kanji: "置き場", hiragana: "おきば", romaji: "okiba", meaning: "tempat meletakkan sampah" },
      { kanji: "横", hiragana: "よこ", romaji: "yoko", meaning: "sebelah, samping" },
      { kanji: "瓶", hiragana: "びん", romaji: "bin", meaning: "botol" },
      { kanji: "缶", hiragana: "かん", romaji: "kan", meaning: "kaleng" },
      { hiragana: "ガス", romaji: "gasu", meaning: "gas" },
      { kanji: "〜会社", hiragana: "〜がいしゃ", romaji: "~gaisha", meaning: "perusahaan ~" },
      { kanji: "宇宙", hiragana: "うちゅう", romaji: "uchuu", meaning: "angkasa" },
      { kanji: "〜様", hiragana: "〜さま", romaji: "~sama", meaning: "kepada Yth. ~, Bapak ~, Ibu ~, Sdr.~ (Kata Hormat dari 〜さん)" },
      { kanji: "宇宙船", hiragana: "うちゅうせん", romaji: "uchuusen", meaning: "wahana antariksa" },
      { kanji: "怖い", hiragana: "こわい", romaji: "kowai", meaning: "takut" },
      { kanji: "宇宙ステーション", hiragana: "うちゅうステーション", romaji: "uchuu-sute-shon", meaning: "stasiun luar angkasa" },
      { kanji: "違います", hiragana: "ちがいます", romaji: "chigaimasu", meaning: "tidak benar" },
      { kanji: "宇宙飛行士", hiragana: "うちゅうひこうし", romaji: "uchuu-hikoushi", meaning: "astronot" },
      { kanji: "星出彰彦", hiragana: "ほしであきひこ", romaji: "hoshide akihiko", meaning: "astronot Jepang (1968-)" }
    ]
  },
  {
    id: 27,
    name: "Bab 27",
    cards: [
      { kanji: "飼います", hiragana: "かいます", romaji: "kaimasu", meaning: "memelihara" },
      { kanji: "走ります", hiragana: "はしります", romaji: "hashirimasu", meaning: "berlari [jalan] [道を〜]" },
      { kanji: "見えます", hiragana: "みえます", romaji: "miemasu", meaning: "[gunung] terlihat [山が〜]" },
      { kanji: "聞こえます", hiragana: "きこえます", romaji: "kikoemasu", meaning: "[bunyi] terdengar [音が〜]" },
      { kanji: "できます", hiragana: "できます", romaji: "dekimasu", meaning: "[jalan] dibuat [道が〜]" },
      { kanji: "開きます", hiragana: "ひらきます", romaji: "hirakimasu", meaning: "membuka/mengadakan [kelas] [教室を〜]" },
      { kanji: "心配[な]", hiragana: "しんぱい[な]", romaji: "shinpai[na]", meaning: "khawatir" },
      { hiragana: "ペット", romaji: "petto", meaning: "hewan peliharaan" },
      { kanji: "鳥", hiragana: "とり", romaji: "tori", meaning: "burung" },
      { kanji: "声", hiragana: "こえ", romaji: "koe", meaning: "suara" },
      { kanji: "波", hiragana: "なみ", romaji: "nami", meaning: "ombak, gelombang" },
      { kanji: "花火", hiragana: "はなび", romaji: "hanabi", meaning: "kembang api" },
      { kanji: "道具", hiragana: "どうぐ", romaji: "dougu", meaning: "alat" },
      { hiragana: "クリーニング", romaji: "kuriiningu", meaning: "laundry" },
      { kanji: "家", hiragana: "いえ", romaji: "ie", meaning: "rumah" },
      { hiragana: "マンション", romaji: "manshon", meaning: "apartmen" },
      { hiragana: "キッチン", romaji: "kicchin", meaning: "dapur" },
      { kanji: "〜教室", hiragana: "〜きょうしつ", romaji: "~kyoushitsu", meaning: "les ~, kelas ~" },
      { hiragana: "パーティールーム", romaji: "paatiiruumu", meaning: "ruang pesta" },
      { kanji: "方", hiragana: "かた", romaji: "kata", meaning: "orang (Kata Hormat dari ひと)" },
      { kanji: "〜後", hiragana: "〜ご", romaji: "~go", meaning: "setelah ~, sesudah ~" },
      { hiragana: "〜しか", romaji: "~shika", meaning: "hanya ~ (dipakai bersama dengan kata bentuk negatif)" },
      { hiragana: "ほかの", romaji: "hokano", meaning: "lain" },
      { hiragana: "はっきり", romaji: "hakkiri", meaning: "jelas" },
      { kanji: "家具", hiragana: "かぐ", romaji: "kagu", meaning: "perabot rumah, mebel" },
      { kanji: "本棚", hiragana: "ほんだな", romaji: "hondana", meaning: "lemari buku" },
      { hiragana: "いつか", romaji: "itsuka", meaning: "kapan-kapan" },
      { kanji: "建てます", hiragana: "たてます", romaji: "tatemasu", meaning: "membangun" },
      { hiragana: "すばらしい", romaji: "subarashii", meaning: "bagus" },
      { kanji: "子どもたち", hiragana: "こどもたち", romaji: "kodomotachi", meaning: "anak-anak" },
      { kanji: "大好き[な]", hiragana: "だいすき[な]", romaji: "daisuki[na]", meaning: "kesukaan" },
      { kanji: "主人公", hiragana: "しゅじんこう", romaji: "shujinkou", meaning: "pelaku utama" },
      { kanji: "形", hiragana: "かたち", romaji: "katachi", meaning: "sosok, bentuk" },
      { kanji: "不思議[な]", hiragana: "ふしぎ[な]", romaji: "fushigi[na]", meaning: "ajaib" },
      { hiragana: "ポケット", romaji: "poketto", meaning: "kantong" },
      { kanji: "例えば", hiragana: "たとえば", romaji: "tatoeba", meaning: "misalnya" },
      { kanji: "付けます", hiragana: "つけます", romaji: "tsukemasu", meaning: "memasang" },
      { kanji: "自由に", hiragana: "じゆうに", romaji: "jiyuuni", meaning: "dengan bebas" },
      { kanji: "空", hiragana: "そら", romaji: "sora", meaning: "langit" },
      { kanji: "飛びます", hiragana: "とびます", romaji: "tobimasu", meaning: "terbang" },
      { kanji: "昔", hiragana: "むかし", romaji: "mukashi", meaning: "dulu" },
      { kanji: "自分", hiragana: "じぶん", romaji: "jibun", meaning: "diri sendiri" },
      { kanji: "将来", hiragana: "しょうらい", romaji: "shourai", meaning: "masa depan" },
      { hiragana: "ドラえもん", romaji: "doraemon", meaning: "nama peran komik" }
    ]
  },
  {
    id: 28,
    name: "Bab 28",
    cards: [
      { kanji: "売れます", hiragana: "うれます", romaji: "uremasu", meaning: "[roti] terjual [パンが〜]" },
      { kanji: "踊ります", hiragana: "おどります", romaji: "odorimasu", meaning: "menari" },
      { kanji: "かみます", hiragana: "かみます", romaji: "kamimasu", meaning: "makan, menggigit" },
      { kanji: "選びます", hiragana: "えらびます", romaji: "erabimasu", meaning: "memilih" },
      { kanji: "通います", hiragana: "かよいます", romaji: "kayoimasu", meaning: "pergi [ke universitas] [大学に〜]" },
      { kanji: "メモします", hiragana: "めもします", romaji: "memoshimasu", meaning: "mencatat" },
      { kanji: "まじめ[な]", hiragana: "まじめ[な]", romaji: "majime[na]", meaning: "serius" },
      { kanji: "熱心[な]", hiragana: "ねっしん[な]", romaji: "nesshin[na]", meaning: "tekun" },
      { kanji: "偉い", hiragana: "えらい", romaji: "erai", meaning: "hebat" },
      { hiragana: "ちょうどいい", romaji: "choudoii", meaning: "pas, cocok" },
      { kanji: "景色", hiragana: "けしき", romaji: "keshiki", meaning: "pemandangan" },
      { kanji: "美容院", hiragana: "びよういん", romaji: "biyouin", meaning: "salon kecantikan" },
      { kanji: "台所", hiragana: "だいどころ", romaji: "daidokoro", meaning: "dapur" },
      { kanji: "経験", hiragana: "けいけん", romaji: "keiken", meaning: "pengalaman (〜があります：berpengalaman, 〜を します：mengalami)" },
      { kanji: "力", hiragana: "ちから", romaji: "chikara", meaning: "tenaga" },
      { kanji: "人気", hiragana: "にんき", romaji: "ninki", meaning: "populer/disenangi ([がくせいに] 〜があります： populer [di kalangan mahasiswa])" },
      { kanji: "形", hiragana: "かたち", romaji: "katachi", meaning: "bentuk, sosok" },
      { kanji: "色", hiragana: "いろ", romaji: "iro", meaning: "warna" },
      { kanji: "味", hiragana: "あじ", romaji: "aji", meaning: "rasa" },
      { hiragana: "ガム", romaji: "gamu", meaning: "permen karet" },
      { kanji: "品物", hiragana: "しなもの", romaji: "shinamono", meaning: "barang" },
      { kanji: "値段", hiragana: "ねだん", romaji: "nedan", meaning: "harga" },
      { kanji: "給料", hiragana: "きゅうりょう", romaji: "kyuuryou", meaning: "gaji" },
      { hiragana: "ボーナス", romaji: "boonasu", meaning: "bonus" },
      { hiragana: "ゲーム", romaji: "geemu", meaning: "permainan, game" },
      { kanji: "番組", hiragana: "ばんぐみ", romaji: "bangumi", meaning: "acara TV" },
      { hiragana: "ドラマ", romaji: "dorama", meaning: "drama" },
      { kanji: "歌手", hiragana: "かしゅ", romaji: "kashu", meaning: "penyanyi" },
      { kanji: "小説", hiragana: "しょうせつ", romaji: "shousetsu", meaning: "novel" },
      { kanji: "小説家", hiragana: "しょうせつか", romaji: "shousetsuka", meaning: "novelis" },
      { kanji: "〜家", hiragana: "〜か", romaji: "~ka", meaning: "aliran ~" },
      { kanji: "〜機", hiragana: "〜き", romaji: "~ki", meaning: "mesin ~" },
      { kanji: "息子", hiragana: "むすこ", romaji: "musuko", meaning: "anak laki-laki" },
      { kanji: "息子さん", hiragana: "むすこさん", romaji: "musukosan", meaning: "putra" },
      { kanji: "娘", hiragana: "むすめ", romaji: "musume", meaning: "anak perempuan" },
      { kanji: "娘さん", hiragana: "むすめさん", romaji: "musumesan", meaning: "putri" },
      { kanji: "自分", hiragana: "じぶん", romaji: "jibun", meaning: "diri sendiri" },
      { kanji: "将来", hiragana: "しょうらい", romaji: "shourai", meaning: "masa depan" },
      { hiragana: "しばらく", romaji: "shibaraku", meaning: "sebentar, sementara" },
      { hiragana: "たいてい", romaji: "taitei", meaning: "kebanyakan" },
      { hiragana: "それに", romaji: "soreni", meaning: "dan juga" },
      { hiragana: "それで", romaji: "sorede", meaning: "dan, lalu" },
      { kanji: "［ちょっと］お願いがあるんですが。", hiragana: "［ちょっと］おねがいがあるんですが。", romaji: "[chotto] onegaiga arundesuga.", meaning: "Minta sesuatu [sebentar]" },
      { kanji: "実は", hiragana: "じつは", romaji: "jitsuha", meaning: "soalnya/sebenarnya" },
      { kanji: "会話", hiragana: "かいわ", romaji: "kaiwa", meaning: "percakapan" },
      { hiragana: "うーん", romaji: "uun", meaning: "mmm..." },
      { kanji: "お知らせ", hiragana: "おしらせ", romaji: "oshirase", meaning: "pemberitahuan, pengumuman" },
      { kanji: "参加します", hiragana: "さんかします", romaji: "sankashimasu", meaning: "mengikuti" },
      { kanji: "日にち", hiragana: "ひにち", romaji: "hinichi", meaning: "tanggal" },
      { kanji: "土", hiragana: "ど", romaji: "do", meaning: "hari Sabtu" },
      { kanji: "体育館", hiragana: "たいいくかん", romaji: "taiikukan", meaning: "gedung olahraga" },
      { kanji: "無料", hiragana: "むりょう", romaji: "muryou", meaning: "gratis, cuma-cuma" },
      { kanji: "誘います", hiragana: "さそいます", romaji: "sasoimasu", meaning: "mengajak" },
      { hiragana: "イベント", romaji: "ibento", meaning: "acara" }
    ]
  }
];


import { irodoriChapters } from "./data/irodoriChapters";
import { irodoriA2Chapters } from "./data/irodoriA2Chapters";
import { irodoriA2_2Chapters } from "./data/irodoriA2_2Chapters";

export const chapters = [...baseChapters, ...irodoriChapters, ...irodoriA2Chapters, ...irodoriA2_2Chapters];
